// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package c.s.l.network.proto;

public final class MessageStub {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Message_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Message_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\rmessage.proto\"\264\001\n\007Message\022\031\n\003cmd\030\001 \001(\016" +
                        "2\014.Message.CMD\022\n\n\002id\030\002 \001(\004\022\016\n\006userId\030\003 \001" +
                        "(\005\022\013\n\003msg\030\004 \001(\t\022\014\n\004data\030\005 \001(\t\"W\n\003CMD\022\010\n\004" +
                        "NONE\020\000\022\014\n\010REGISTER\020\001\022\017\n\013HEART_BLOOD\020\002\022\013\n" +
                        "\007MESSAGE\020\003\022\t\n\005CLOSE\020\004\022\017\n\013CLIENT_INFO\020\005B#" +
                        "\n\023c.s.l.network.protoB\014MessageStub b\006pro" +
                        "to3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_Message_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Message_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Message_descriptor,
                new java.lang.String[]{"Cmd", "Id", "UserId", "Msg", "Data",});
    }

    private MessageStub() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface MessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Message)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.Message.CMD cmd = 1;</code>
         */
        int getCmdValue();

        /**
         * <code>.Message.CMD cmd = 1;</code>
         */
        c.s.l.network.proto.MessageStub.Message.CMD getCmd();

        /**
         * <code>uint64 id = 2;</code>
         */
        long getId();

        /**
         * <code>int32 userId = 3;</code>
         */
        int getUserId();

        /**
         * <code>string msg = 4;</code>
         */
        java.lang.String getMsg();

        /**
         * <code>string msg = 4;</code>
         */
        com.google.protobuf.ByteString
        getMsgBytes();

        /**
         * <code>string data = 5;</code>
         */
        java.lang.String getData();

        /**
         * <code>string data = 5;</code>
         */
        com.google.protobuf.ByteString
        getDataBytes();
    }

    /**
     * Protobuf type {@code Message}
     */
    public static final class Message extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Message)
            MessageOrBuilder {
        public static final int CMD_FIELD_NUMBER = 1;
        public static final int ID_FIELD_NUMBER = 2;
        public static final int USERID_FIELD_NUMBER = 3;
        public static final int MSG_FIELD_NUMBER = 4;
        public static final int DATA_FIELD_NUMBER = 5;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:Message)
        private static final c.s.l.network.proto.MessageStub.Message DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Message>
                PARSER = new com.google.protobuf.AbstractParser<Message>() {
            @java.lang.Override
            public Message parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Message(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new c.s.l.network.proto.MessageStub.Message();
        }

        private int cmd_;
        private long id_;
        private int userId_;
        private volatile java.lang.Object msg_;
        private volatile java.lang.Object data_;
        private byte memoizedIsInitialized = -1;

        // Use Message.newBuilder() to construct.
        private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Message() {
            cmd_ = 0;
            id_ = 0L;
            userId_ = 0;
            msg_ = "";
            data_ = "";
        }

        private Message(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            int rawValue = input.readEnum();

                            cmd_ = rawValue;
                            break;
                        }
                        case 16: {

                            id_ = input.readUInt64();
                            break;
                        }
                        case 24: {

                            userId_ = input.readInt32();
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            msg_ = s;
                            break;
                        }
                        case 42: {
                            java.lang.String s = input.readStringRequireUtf8();

                            data_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return c.s.l.network.proto.MessageStub.internal_static_Message_descriptor;
        }

        public static c.s.l.network.proto.MessageStub.Message parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static c.s.l.network.proto.MessageStub.Message parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static c.s.l.network.proto.MessageStub.Message parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static c.s.l.network.proto.MessageStub.Message parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static c.s.l.network.proto.MessageStub.Message parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static c.s.l.network.proto.MessageStub.Message parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static c.s.l.network.proto.MessageStub.Message parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static c.s.l.network.proto.MessageStub.Message parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static c.s.l.network.proto.MessageStub.Message parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static c.s.l.network.proto.MessageStub.Message parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static c.s.l.network.proto.MessageStub.Message parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static c.s.l.network.proto.MessageStub.Message parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(c.s.l.network.proto.MessageStub.Message prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static c.s.l.network.proto.MessageStub.Message getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Message> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return c.s.l.network.proto.MessageStub.internal_static_Message_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            c.s.l.network.proto.MessageStub.Message.class, c.s.l.network.proto.MessageStub.Message.Builder.class);
        }

        /**
         * <code>.Message.CMD cmd = 1;</code>
         */
        public int getCmdValue() {
            return cmd_;
        }

        /**
         * <code>.Message.CMD cmd = 1;</code>
         */
        public c.s.l.network.proto.MessageStub.Message.CMD getCmd() {
            @SuppressWarnings("deprecation")
            c.s.l.network.proto.MessageStub.Message.CMD result = c.s.l.network.proto.MessageStub.Message.CMD.valueOf(cmd_);
            return result == null ? c.s.l.network.proto.MessageStub.Message.CMD.UNRECOGNIZED : result;
        }

        /**
         * <code>uint64 id = 2;</code>
         */
        public long getId() {
            return id_;
        }

        /**
         * <code>int32 userId = 3;</code>
         */
        public int getUserId() {
            return userId_;
        }

        /**
         * <code>string msg = 4;</code>
         */
        public java.lang.String getMsg() {
            java.lang.Object ref = msg_;
            return getString(ref);
        }

        private String getString(Object ref) {
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                msg_ = s;
                return s;
            }
        }

        /**
         * <code>string msg = 4;</code>
         */
        public com.google.protobuf.ByteString
        getMsgBytes() {
            java.lang.Object ref = msg_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                msg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string data = 5;</code>
         */
        public java.lang.String getData() {
            java.lang.Object ref = data_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                data_ = s;
                return s;
            }
        }

        /**
         * <code>string data = 5;</code>
         */
        public com.google.protobuf.ByteString
        getDataBytes() {
            java.lang.Object ref = data_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                data_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (cmd_ != c.s.l.network.proto.MessageStub.Message.CMD.NONE.getNumber()) {
                output.writeEnum(1, cmd_);
            }
            if (id_ != 0L) {
                output.writeUInt64(2, id_);
            }
            if (userId_ != 0) {
                output.writeInt32(3, userId_);
            }
            if (!getMsgBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msg_);
            }
            if (!getDataBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, data_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (cmd_ != c.s.l.network.proto.MessageStub.Message.CMD.NONE.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, cmd_);
            }
            if (id_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(2, id_);
            }
            if (userId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, userId_);
            }
            if (!getMsgBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msg_);
            }
            if (!getDataBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, data_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof c.s.l.network.proto.MessageStub.Message)) {
                return super.equals(obj);
            }
            c.s.l.network.proto.MessageStub.Message other = (c.s.l.network.proto.MessageStub.Message) obj;

            boolean result = true;
            result = result && cmd_ == other.cmd_;
            result = result && (getId()
                    == other.getId());
            result = result && (getUserId()
                    == other.getUserId());
            result = result && getMsg()
                    .equals(other.getMsg());
            result = result && getData()
                    .equals(other.getData());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CMD_FIELD_NUMBER;
            hash = (53 * hash) + cmd_;
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getId());
            hash = (37 * hash) + USERID_FIELD_NUMBER;
            hash = (53 * hash) + getUserId();
            hash = (37 * hash) + MSG_FIELD_NUMBER;
            hash = (53 * hash) + getMsg().hashCode();
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Message> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public c.s.l.network.proto.MessageStub.Message getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf enum {@code Message.CMD}
         */
        public enum CMD
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>NONE = 0;</code>
             */
            NONE(0),
            /**
             * <code>REGISTER = 1;</code>
             */
            REGISTER(1),
            /**
             * <code>HEART_BLOOD = 2;</code>
             */
            HEART_BLOOD(2),
            /**
             * <code>MESSAGE = 3;</code>
             */
            MESSAGE(3),
            /**
             * <code>CLOSE = 4;</code>
             */
            CLOSE(4),
            /**
             * <code>CLIENT_INFO = 5;</code>
             */
            CLIENT_INFO(5),
            UNRECOGNIZED(-1),
            ;

            /**
             * <code>NONE = 0;</code>
             */
            public static final int NONE_VALUE = 0;
            /**
             * <code>REGISTER = 1;</code>
             */
            public static final int REGISTER_VALUE = 1;
            /**
             * <code>HEART_BLOOD = 2;</code>
             */
            public static final int HEART_BLOOD_VALUE = 2;
            /**
             * <code>MESSAGE = 3;</code>
             */
            public static final int MESSAGE_VALUE = 3;
            /**
             * <code>CLOSE = 4;</code>
             */
            public static final int CLOSE_VALUE = 4;
            /**
             * <code>CLIENT_INFO = 5;</code>
             */
            public static final int CLIENT_INFO_VALUE = 5;
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    CMD> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<CMD>() {
                        public CMD findValueByNumber(int number) {
                            return CMD.forNumber(number);
                        }
                    };
            private static final CMD[] VALUES = values();
            private final int value;

            CMD(int value) {
                this.value = value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static CMD valueOf(int value) {
                return forNumber(value);
            }

            public static CMD forNumber(int value) {
                switch (value) {
                    case 0:
                        return NONE;
                    case 1:
                        return REGISTER;
                    case 2:
                        return HEART_BLOOD;
                    case 3:
                        return MESSAGE;
                    case 4:
                        return CLOSE;
                    case 5:
                        return CLIENT_INFO;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<CMD>
            internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return c.s.l.network.proto.MessageStub.Message.getDescriptor().getEnumTypes().get(0);
            }

            public static CMD valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                if (this == UNRECOGNIZED) {
                    throw new java.lang.IllegalArgumentException(
                            "Can't get the number of an unknown enum value.");
                }
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:Message.CMD)
        }

        /**
         * Protobuf type {@code Message}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Message)
                c.s.l.network.proto.MessageStub.MessageOrBuilder {
            private int cmd_ = 0;
            private long id_;
            private int userId_;
            private java.lang.Object msg_ = "";
            private java.lang.Object data_ = "";

            // Construct using c.s.l.network.proto.MessageStub .Message.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return c.s.l.network.proto.MessageStub.internal_static_Message_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return c.s.l.network.proto.MessageStub.internal_static_Message_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                c.s.l.network.proto.MessageStub.Message.class, c.s.l.network.proto.MessageStub.Message.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                cmd_ = 0;

                id_ = 0L;

                userId_ = 0;

                msg_ = "";

                data_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return c.s.l.network.proto.MessageStub.internal_static_Message_descriptor;
            }

            @java.lang.Override
            public c.s.l.network.proto.MessageStub.Message getDefaultInstanceForType() {
                return c.s.l.network.proto.MessageStub.Message.getDefaultInstance();
            }

            @java.lang.Override
            public c.s.l.network.proto.MessageStub.Message build() {
                c.s.l.network.proto.MessageStub.Message result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public c.s.l.network.proto.MessageStub.Message buildPartial() {
                c.s.l.network.proto.MessageStub.Message result = new c.s.l.network.proto.MessageStub.Message(this);
                result.cmd_ = cmd_;
                result.id_ = id_;
                result.userId_ = userId_;
                result.msg_ = msg_;
                result.data_ = data_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof c.s.l.network.proto.MessageStub.Message) {
                    return mergeFrom((c.s.l.network.proto.MessageStub.Message) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(c.s.l.network.proto.MessageStub.Message other) {
                if (other == c.s.l.network.proto.MessageStub.Message.getDefaultInstance()) return this;
                if (other.cmd_ != 0) {
                    setCmdValue(other.getCmdValue());
                }
                if (other.getId() != 0L) {
                    setId(other.getId());
                }
                if (other.getUserId() != 0) {
                    setUserId(other.getUserId());
                }
                if (!other.getMsg().isEmpty()) {
                    msg_ = other.msg_;
                    onChanged();
                }
                if (!other.getData().isEmpty()) {
                    data_ = other.data_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                c.s.l.network.proto.MessageStub.Message parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (c.s.l.network.proto.MessageStub.Message) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>.Message.CMD cmd = 1;</code>
             */
            public int getCmdValue() {
                return cmd_;
            }

            /**
             * <code>.Message.CMD cmd = 1;</code>
             */
            public Builder setCmdValue(int value) {
                cmd_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>.Message.CMD cmd = 1;</code>
             */
            public c.s.l.network.proto.MessageStub.Message.CMD getCmd() {
                @SuppressWarnings("deprecation")
                c.s.l.network.proto.MessageStub.Message.CMD result = c.s.l.network.proto.MessageStub.Message.CMD.valueOf(cmd_);
                return result == null ? c.s.l.network.proto.MessageStub.Message.CMD.UNRECOGNIZED : result;
            }

            /**
             * <code>.Message.CMD cmd = 1;</code>
             */
            public Builder setCmd(c.s.l.network.proto.MessageStub.Message.CMD value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                cmd_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>.Message.CMD cmd = 1;</code>
             */
            public Builder clearCmd() {

                cmd_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 id = 2;</code>
             */
            public long getId() {
                return id_;
            }

            /**
             * <code>uint64 id = 2;</code>
             */
            public Builder setId(long value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 id = 2;</code>
             */
            public Builder clearId() {

                id_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>int32 userId = 3;</code>
             */
            public int getUserId() {
                return userId_;
            }

            /**
             * <code>int32 userId = 3;</code>
             */
            public Builder setUserId(int value) {

                userId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 userId = 3;</code>
             */
            public Builder clearUserId() {

                userId_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string msg = 4;</code>
             */
            public java.lang.String getMsg() {
                java.lang.Object ref = msg_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    msg_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string msg = 4;</code>
             */
            public Builder setMsg(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                msg_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string msg = 4;</code>
             */
            public com.google.protobuf.ByteString
            getMsgBytes() {
                java.lang.Object ref = msg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    msg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string msg = 4;</code>
             */
            public Builder setMsgBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                msg_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string msg = 4;</code>
             */
            public Builder clearMsg() {

                msg_ = getDefaultInstance().getMsg();
                onChanged();
                return this;
            }

            /**
             * <code>string data = 5;</code>
             */
            public java.lang.String getData() {
                java.lang.Object ref = data_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    data_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string data = 5;</code>
             */
            public Builder setData(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                data_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string data = 5;</code>
             */
            public com.google.protobuf.ByteString
            getDataBytes() {
                java.lang.Object ref = data_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    data_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string data = 5;</code>
             */
            public Builder setDataBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                data_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string data = 5;</code>
             */
            public Builder clearData() {

                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Message)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
